project:
  type: book
  output-dir: _book
  
lang: de

book:
  title: "Mikroorganismen im Sand und deren Auswirkung auf die Umwelt"
  author:
    - name: "Jasper Meiners"
      orcid: ""
      email: "Jasper.Meiners@icloud.com"
      corresponding: true
      roles: "Lead author"
      affiliation:
        - id: AG
        - name: "Altes Gymnasium Bremen"
          city: "Bremen"
          state: "Germany"
          url: "https://www.altes-gymnasium-bremen.de/deutsch/start.php"
          
  date: last-modified
#  license: "Apache-2.0 license"

  reader-mode: true

  page-footer:
    left: |
      BundesUmweltWettbewerb 2027, J. Meiners, Altes Gymnasium Bremen
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/ag-logo.png
#  favicon: images/ag-logo.png
  site-url: https://jameiners.github.io/buw/
  repo-url: https://github.com/jameiners/buw/
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf]
    
  chapters:
    - index.qmd
    - 01_intro.qmd
    - references.qmd
       
  output-file: "buw"

# Bibliography
bibliography: bibliography/references.bib
# csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
csl: bibliography/ieee.csl

execute:
  # freeze: true
  enabled: true

format:
  html:
    theme: flatly
    fontsize: 1.2em
    linestretch: 1.7
    # mainfont: Helvetica Neue, Helvetica, Arial, sans
    # monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    # backgroundcolor: "white"
    # fontcolor: "black"
    highlight-style: github

  # epub:
  #   theme: flatly
  #   fontsize: 1.2em
  #   linestretch: 1.7
  #   # mainfont: Helvetica Neue, Helvetica, Arial, sans
  #   # monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
  #   # backgroundcolor: "white"
  #   # fontcolor: "black"
  #   highlight-style: github

  typst: default

  # pdf:
  #   documentclass: scrbook
  #   classoption: [twoside]

  #   keep-tex: true

  #   toc: true
  #   toc-depth: 3
  #   # toc-title: "Table of contents"
  #   # lof: true
  #   # lot: true

  #   number-sections: true
  #   number-depth: 2
        
  #   papersize: a4
        
  #   geometry:
  #     - inner=3cm
  #     - outer=4cm
  #     - top=3cm
  #     - bottom=4cm
  #     - headsep=22pt
  #     - headheight=11pt
  #     - footskip=33pt
  #     - ignorehead
  #     - ignorefoot
  #     - heightrounded

  #   fontsize: 14pt
  #   pdfengine: xelatex

  #   mainfont: "Times New Roman"
  #   sansfont: "Arial"
  #   monofont: "Courier New"
  #   mathfont: "TeX Gyre Termes Math"
  #   highlight-style: pygments
    
  #   # include-in-header:
  #   #   - frontmatter/header.tex
  #   # template-partials:
  #   # - frontmatter/before-body.tex
  #   # - frontmatter/toc.tex
