# Einleitung

## Lernziele des Moduls

* Einblicke in (mikro-)elektronische Systeme

* Analyse und Funktion von Halbleiterbauelementen
  * Halbleiterphysik
  * Modellbildung
  * Netzwerkanalyse/-synthese

* Anwendung von SPICE in der Schaltunganalyse
  * Spezifikation
  * Partitionierung
  * Design

* Einsatz von Entwicklungsboards, Embedded Systems / System-on-Chip (SoC)
  * STEMlab von [Red Pitaya](https://www.redpitaya.com)

## Wissenschaftliches Rechnen / Datenwissenschaft

* [Python](https://www.anaconda.com/download/)

* [Matlab](https://de.mathworks.com)

* [Command-line tools](https://jeroenjanssens.com/dsatcl/) 


## EDA Tools

-   PCB / System Design
    -   [LTspice](https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html)
    -   [KiCad EDA](https://www.kicad.org/)
    -   [Altium Designer](https://www.altium.com/de/altium-designer)
    -   [SiemensEDA PCB tools](https://eda.sw.siemens.com/en-US/pcb/products/)
    -   [cadence System Design & Analysis](https://www.cadence.com/en_US/home/tools/system-design-and-analysis.html)
-   IC / Silicon Design
    -   [IIC-OSIC-TOOLS (open-source)](https://github.com/iic-jku/IIC-OSIC-TOOLS)
    -   [SiemensEDA IC tools](https://eda.sw.siemens.com/en-US/ic/products/)
    -   [cadence IC Design & Verification](https://www.cadence.com/en_US/home/tools/design-excellence.html)
    -   [synopsys silicon design (IC)](https://www.synopsys.com/silicon-design.html)


## Betriebssystem (OS) - Werkzeuge (Tools)
* [SSH (Secure Shell)](https://de.wikipedia.org/wiki/Secure_Shell)
* [Microsoft-Terminal](https://github.com/microsoft/terminal)
* [Microsoft-PowerShell](https://learn.microsoft.com/de-de/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.4)
* [MacOS-Terminal](https://iterm2.com)
* [Linux/MacOS zsh-tools](https://ohmyz.sh)
* [Linux/MacOS bash-it](https://bash-it.readthedocs.io/en/latest/)
* [Git (Versionskontrolle)](https://git-scm.com)
* [TortoiseGit – Windows Shell Interface to Git](https://tortoisegit.org/)


## Code Editoren
* [Visual Studio Code](https://code.visualstudio.com)
* [Spyder IDE](https://www.spyder-ide.org)
* [Thonny (Micro-)Python IDE](https://thonny.org)
* [Emacs](https://www.gnu.org/software/emacs/)
* [Vim](https://www.vim.org)


## Berichtswesen / Laborberichte

* [quarto](https://quarto.org)
   * [Manuscripts](https://quarto.org/docs/manuscripts/)

* LaTeX
  * [MikTeX (Windows, MacOS, Linux)](https://miktex.org/)
  * [MacTeX (MacOS)](https://www.tug.org/mactex/)
  * [TeXLive (Linux)](http://tug.org/texlive/)

* LaTeX Editoren
  * [TeXStudio](http://www.texstudio.org)
  * [TeXMaker](http://www.xm1math.net/texmaker/)
  * [TeXWorks](http://www.tug.org/texworks/)

* Kollaborative Frameworks
  * [ShareLaTeX, Online LaTeX](https://www.sharelatex.com/)
  * [CoCalc - Online LaTeX](https://cocalc.com/doc/latex-editor.html)
	* ein Service der [AcademicCloud](https://academiccloud.de)

* Literaturverwaltung
  * [Zotero](https://www.suub.uni-bremen.de/service-beratung/literaturverwaltung/zotero/) 
  * [Citavi](https://www.suub.uni-bremen.de/service-beratung/literaturverwaltung/citavi-2/)

* Datenverarbeitung
  * Dateisystem Ordner und Dateien
  * Comma-Separated-Values (CSV), Tab-Separated-Values (TSV)
	* [csvkit](https://github.com/wireservice/csvkit)
	* [miller](https://github.com/johnkerl/miller)
  * Spreadsheet (.xlsx, .ods)


## Experimentelle Arbeit - Entwurf elektronischer Systeme

Analyse und Synthese von elektronischen Bauelementen und Systemen mit 

* Modellbildung auf Systemebene / Verhaltensmodellierung
  
* Simulation auf Schaltungsebene / SPICE

* Charakterisierung auf Hardwareebene mit

  * [Analog System Lab Kit (ASLK) Pro](https://aslk-pro.readthedocs.io/de/latest/)

  * [Red Pitaya's STEMlab 125-14/10](https://redpitaya.readthedocs.io/en/latest/developerGuide/125-14/top.html)

* Technische Dokumentation mit [quarto](https://quarto.org)


## Reiseaussichten

Dies ist der **Beginn eines Prozesses**,

besser noch, **eines Abenteuers**.


## Reiseziele

* Mehr über Signale wissen, die in elektronischen Systemen verarbeitet werden.

* Schaltungsdiagramme lesen können.

* Wissen über grundlegende Blöcke eines Systems aneignen.

* Wissen, wie Transistoren arbeiten und in modernen integrierten Technologien hergestellt werden.

* Eigenarten der Modellierung mikroelektronischer Bauelemente und der physikalischen und chemischen Prinzipien im
  Herstellungsprozess kennenlernen. 


## Reisebedingungen

*Anwendung Ihres Werkzeugkastens.* 
* Grundlagen der Elektrotechnik/Physik

* Elektromagnetische Wellen

* Angewandte Mathematik und Systemtheorie

* Trainingswille

* Pioniergeist

* Spa{\ss}


*Schnallen Sie sich an, die Reise beginnt ...*


## Halbleiterherstellung (Infineon, Dresden)

{{< video "https://www.youtube.com/embed/_Kj58yQ67KI" width="854" height="480">}}


## FinFET (Intel)

{{< video "https://www.youtube.com/embed/_VMYPLXnd7E" width="854" height="480">}}


## TSMC Fab (Next Gen 7/5 nm)

{{< video "https://www.youtube.com/embed/Hb1WDxSoSec" width="854" height="480" >}}


## Sie werden Experte

*Leistungsmerkmale.* 

* Hintergrundwissen
  * Systemverständnis, Architektur, Herstellungsverfahren, Implementation

* Unterbewusste Kompetenz
  * Abgespeicherte Erfahrungen aus Erfolgsgeschichten und Misserfolgen

* Spezialwissen
  * Berufsspezifisches Wissen

* Teamwork Haltung
  * Kommunikationsfähigkeit, Berichtswesen und technische Präsentation

* Kreativität

* Tool-Kenntnisse


## Evolution von Produkten

* Angetrieben durch Technologieverbesserung
  * Kosten (größere Chips, geringere Größe der Merkmale, bessere Ausbeute)
  * Leistung (neue Bauteile, höhere Geschwindigkeit, weniger Stromverbrauch)

* Angetrieben durch Verbesserung der Entwurfsmethodik
  * Architektur (Leistung, Funktionen)
  * CAD (Entwicklungskosten, Time-to-Market)

* Komplexität der Designs verdoppelt sich jedes Jahr (Moore's Gesetz)

* Rolle von CAD
  * Verbesserung der Produktivität von Konstruktionsprozessen
  * Reduzierung der Komplexität für den Konstrukteur
  * Sicherstellung des ordnungsgemäßen Betriebs der Geräte


## EDA Kompetenz

* EDA-Anbieter (Tool-Entwickler)
  * Identifikation von Entwurfsaufgaben, Bedarf an Werkzeugen
  * Entwicklung von Strategien und Algorithmen
  * Implementierung von Software-Werkzeugen
  * Verifikation der Stabilität und Funktionalität der Software-Tools

* IC-Hersteller
  * Entscheidungsplanung, welches Tool die Produktivität steigern könnte
  * EDA-Tool-Manager, Installation und Wartung
  * Experten für Softwareeinsatz, Anwendung in Produktdesign und -entwicklung

* Dozenten und Studenten
  * Jobchancen
  * Notwendigkeit, auf dem Laufenden zu bleiben


## Design-/Entwurfsmethodik

* Full Custom - vollständig manuell: ASIC
  * Überwiegend analoge Schaltungen
  * Einfache digitale Gatter
  * Volle Kontrolle, aber lange Entwicklungszeit (bis zu Jahren)

* Semi-custom: ASIC-Fertigung mit Verwendung von vorgefertigten Teilen
  * Standardzellen, Makrozellen, IP's
  * Wiederverwendung von vordefinierten Blöcken oder Maskensätzen
  * Eingeschränkte Kontrolle/Flexibilität, aber kürzere Entwicklungszeit (bis zu Wochen)

* Vollständig automatisiert: Keine Fertigung, reprogrammierbare ASICs
  * FPGA, PLA
  * Ausschließlich digitale Schaltungen
  * Schnelles Prototyping
